[versions]
agp = "8.9.1"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
gson = "2.10"
retrofit = "2.9.0"
converter-gson = "2.9.0"
glide = "4.14.2"
glide-compiler = "4.14.2"
activity-ktx = "1.6.1"
lifecycle-viewmodel-ktx = "2.5.1"
lifecycle-livedata-ktx = "2.5.1"
koinAndroid = "3.3.0"
viewpager2 = "1.0.0"
navigation-ui-ktx = "2.5.3"
navigation-fragment-ktx = "2.5.3"
fragment-ktx = "1.5.6"
coroutines-android = "1.7.3"
room = "2.6.0"
room-compiler = "2.6.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converter-gson" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name= "compiler", version.ref = "glide-compiler" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle" , name = "lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle" , name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
activity-ktx = { group = "androidx.activity" , name = "activity-ktx", version.ref = "activity-ktx" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
navigation-ui-ktx = { group="androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx"}
navigation-fragment-ktx = { group = "androidx.navigation", name="navigation-fragment-ktx", version.ref="navigation-fragment-ktx"}
fragment-ktx = { group = "androidx.fragment", name="fragment-ktx", version.ref="fragment-ktx"}
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref="coroutines-android"}
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref="room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref="room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-compiler"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

